---

- name: Finder - show hidden files
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: "true"
  notify: killall finder

- name: Finder - show file extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: "true"
  notify: killall finder

- name: Finder - show status bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: "true"
  notify: killall finder

- name: Finder - show path bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "true"
  notify: killall finder

- name: Finder - use column view by default
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "clmv"
  notify: killall finder
