---

- include: flux.yml
- include: chrome.yml
- include: firefox.yml
- include: virtualbox.yml
- include: vagrant.yml
- include: docker-toolbox.yml
- include: iterm.yml
- include: vlc.yml
- include: dropbox.yml
- include: steam.yml
- include: spectacle.yml
- include: adium.yml
- include: hipchat.yml
- include: rdio.yml
